---
kind: pipeline
name: shell scripts
clone:
  depth: 1
image_pull_secrets:
  - dockerconfig
steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine:v0.7.2
    commands:
      - shellcheck scripts/* githooks/*
  - name: shfmt
    image: mvdan/shfmt:v3.5.1-alpine
    commands:
      - shfmt -d .
---
kind: pipeline
name: yamllint
clone:
  depth: 1
image_pull_secrets:
  - dockerconfig
steps:
  - name: output target files to the file
    image: plugins/git
    commands:
      - 'git ls-files | grep -E ".*\.ya?ml$" > yaml.txt'
  - name: yamllint
    image: quay.io/suzuki_shunsuke/yamllint:1.23.0
    commands:
      - 'cat yaml.txt | xargs yamllint -c .yamllint.yml'
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
image_pull_secrets:
  - dockerconfig
steps:
  - name: download go modules
    image: golang:1.19.1
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: test
    image: golang:1.19.1
    commands:
      - mkdir -p bin
      - curl -L -o bin/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64
      - chmod a+x bin/cc-test-reporter
      - export PATH="$PWD/bin:$PATH"
      - bash scripts/test-code-climate.sh
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    volumes: *volumes
  - name: dry-run
    image: golang:1.19.1
    commands:
      - bash scripts/test-dry-run.sh
    volumes: *volumes
