---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine:v0.7.1
    commands:
      - shellcheck scripts/* githooks/*
  - name: shfmt
    image: mvdan/shfmt:v3.2.0-alpine
    commands:
      - shfmt -d .
---
kind: pipeline
name: yamllint
clone:
  depth: 1
steps:
  - name: output target files to the file
    image: plugins/git
    commands:
      - 'git ls-files | grep -E ".*\.ya?ml$" > yaml.txt'
  - name: yamllint
    image: quay.io/suzuki_shunsuke/yamllint:1.23.0
    commands:
      - 'cat yaml.txt | xargs yamllint -c .yamllint.yml'
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
steps:
  - name: download go modules
    image: golang:1.15.5
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: golangci-lint
    image: golangci/golangci-lint:v1.33.0-alpine
    commands:
      - golangci-lint run
    volumes: *volumes
  - name: test
    image: golang:1.15.5
    commands:
      - mkdir -p bin
      - curl -L -o bin/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64
      - chmod a+x bin/cc-test-reporter
      - export PATH="$PWD/bin:$PATH"
      - bash scripts/test-code-climate.sh
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    volumes: *volumes
  - name: dry-run
    image: golang:1.15.5
    commands:
      - bash scripts/test-dry-run.sh
    volumes: *volumes

  - name: remove changes
    image: &image_git plugins/git
    commands:
      # Sometimes it is failed to release by goreleaser due to changes of go.sum
      - git checkout -- .
  - name: fetch tags to release
    image: *image_git
    commands:
      - git fetch --tags
    when:
      event:
        - tag

  - name: release
    image: goreleaser/goreleaser:v0.150.0
    commands:
      - goreleaser release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes: *volumes
    when:
      event:
        - tag

  - name: release (skip publish)
    image: goreleaser/goreleaser:v0.150.0
    commands:
      - goreleaser release --snapshot
    volumes: *volumes
    when:
      event:
        - pull_request
        - push
