---
run:
  skip-files:
    - "mock\\.go$"
    - "mock_[^/]*\\.go$"
linters:
  enable-all: true
  disable:
    - scopelint # WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
    - interfacer # WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - golint # WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.
    - tagliatelle
    - wsl
    - goerr113
    - nlreturn
    - lll
    - godot
    - exhaustivestruct
    - exhaustruct
    - godox
    - varnamelen
    - ireturn
    - depguard
