---
issues:
  exclude-files:
    - "mock\\.go$"
    - "mock_[^/]*\\.go$"
linters:
  enable-all: true
  disable:
    - exportloopref # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - tagliatelle
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - exhaustruct
    - godox
    - varnamelen
    - ireturn
    - depguard
