---
version: 2
builds:
  - binary: github-comment
    main: cmd/github-comment/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/github-comment/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/github-comment/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/github-comment/compare/{{.PreviousTag}}...{{.Tag}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*

sboms:
  - id: default
    disable: false

homebrew_casks:
  -
    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
    # same kind. We will probably unify this in the next major version like it is done with scoop.

    repository:
      owner: suzuki-shunsuke
      name: homebrew-github-comment
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/suzuki-shunsuke/github-comment
    description: |
      CLI to create and hide GitHub comments
    license: MIT
    skip_upload: true
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-comment"]
          end
