---
name: Deploy GitHub Pages
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/10 * * * *"
permissions: {}
jobs:
  deploy-doc:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: suzuki-shunsuke/github-comment
          persist-credentials: false
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - uses: suzuki-shunsuke/gh-pages-action@6229a3f8d89389da5c234aab3b37ba51a7fee3f6 # v0.0.1
        with:
          publish_dir: ./build
          destination_dir: ./docs

      - uses: suzuki-shunsuke/notify-workflow-error-action@e5e8817e62eb122231d162dbc8309c4d05a21b2e # v0.1.0
        if: always()
        with:
          issue_number: "1892"
          status: ${{ job.status }}
