---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: "1.22.1"
          cache: true
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.25.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run
      - run: go test -v ./... -race -covermode=atomic
