---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: "1.21.4"
          cache: true
      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.16.4
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run
      - run: go test -v ./... -race -covermode=atomic
