---
name: test (workflow_call)
permissions: {}
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@98ab396ba72f7b47f7e22aca7346b6e1d7ae4deb # v6.0.0
    with:
      aqua_version: v2.60.1
      golangci-lint-timeout: 120s
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      pull-requests: write
      contents: read
      id-token: write

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1

      - name: dry run
        run: bash scripts/test-dry-run.sh

  test_deploy_doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: write
      issues: write
      id-token: write
