---
name: test (workflow_call)
permissions: {}
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@6e3ab6f9508fec552b5890e7710d6cdef4489d22 # v6.0.1
    with:
      aqua_version: v2.62.2
      golangci-lint-timeout: 120s
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      pull-requests: write
      contents: read
      id-token: write

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.2

      - name: dry run
        run: bash scripts/test-dry-run.sh

  test_deploy_doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: write
      issues: write
      id-token: write
